name: Docker Image Test Build

on:
  push:
    branches: [ main, dev*, test* ]
  pull_request:
    branches: [ main, dev*, test* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-12, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker colima
        colima start

    - name: Build the Docker image
      if: ${{ matrix.runs-on != 'windows-latest' }}
      run: |
        ls -alt
        docker build -t test_docker -f DockerfileU24 .

        docker -v
        docker images
        ls -alth

    - name: Build the Docker image
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        # See https://github.com/actions/runner/issues/904...
