name: Docker Image Test Build

on:
  push:
    branches: [ main, dev*, test* ]
  pull_request:
    branches: [ main, dev*, test* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        ls -alt
        docker build -t test_docker -f DockerfileU24 .

    - name: Info on Docker images
      run: |
        docker -v
        docker images

    - name: Info on generated files
      run: |
        ls -alth
